# Generated by Django 3.2.5 on 2021-07-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='author',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Автор или авторы'),
        ),
    ]
