# Generated by Django 3.2.5 on 2021-07-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название меню первого уровня')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1200, verbose_name='Название меню второго уровня')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='top', max_length=120, verbose_name='Название меню')),
                ('sub_menu', models.ManyToManyField(related_name='first_menu', to='main.FirstMenu', verbose_name='Меню первого уровня')),
            ],
        ),
        migrations.AddField(
            model_name='firstmenu',
            name='sub_menu',
            field=models.ManyToManyField(related_name='second_menu', to='main.SecondMenu', verbose_name='Меню второго уровня'),
        ),
    ]
