# Generated by Django 3.2.5 on 2021-07-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210720_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='sub_menu',
        ),
        migrations.DeleteModel(
            name='FirstMenu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='SecondMenu',
        ),
    ]
