# Generated by Django 3.2.5 on 2021-07-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пункта меню')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Название пункта меню',
                'verbose_name_plural': 'Названия пункта меню',
            },
        ),
    ]
