# Generated by Django 3.2.5 on 2021-07-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rubric',
            new_name='Rubric_Company',
        ),
    ]
