# Generated by Django 3.2.5 on 2021-07-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_rubric_rubric_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='', verbose_name='Файлы к отыву')),
            ],
            options={
                'verbose_name': 'Файл к отзыву',
                'verbose_name_plural': 'Файлы к отзыву',
            },
        ),
        migrations.RenameModel(
            old_name='Rubric_Company',
            new_name='RubricCompany',
        ),
        migrations.CreateModel(
            name='ReviewsCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Компания')),
                ('content', models.TextField(verbose_name='Текст отзыва')),
                ('publish', models.DateField(auto_now_add=True)),
                ('files', models.ManyToManyField(blank=True, null=True, related_name='reviews_files', to='company.ReviewsFiles')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
