# Generated by Django 3.2.5 on 2021-07-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210720_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewscompany',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватарка'),
        ),
    ]
