# Generated by Django 3.2.5 on 2021-07-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_reviewscompany_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewscompany',
            name='slug',
            field=models.SlugField(default=1, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
