# Generated by Django 3.2.5 on 2021-07-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_reviewscompany_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewscompany',
            name='position',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Должность'),
        ),
    ]
